// Regenerates src/api/schema.d.ts from the FastAPI OpenAPI document, produced directly from
// the backend code (no running server needed). Web types can't drift from the API contract.
import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import openapiTS, { astToString } from 'openapi-typescript'

const json = execFileSync('uv', ['run', 'python', '-c',
  'import json; from app.main import app; print(json.dumps(app.openapi()))'],
  { cwd: new URL('../../backend', import.meta.url), env: { ...process.env, BISTRO_ENVIRONMENT: 'development' } })
const ast = await openapiTS(JSON.parse(json.toString()))
writeFileSync(new URL('../src/api/schema.d.ts', import.meta.url),
  '// Generated by scripts/gen-api.mjs from the FastAPI OpenAPI schema. Do not edit.\n' + astToString(ast))
console.error('wrote src/api/schema.d.ts')
