"""auth session client

Revision ID: 0d815d1f2fd8
Revises: 21ddf79e1b46
Create Date: 2026-09-28 07:15:02.633856
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0d815d1f2fd8'
down_revision: str | None = '21ddf79e1b46'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_sessions', sa.Column('client', sa.String(length=10), server_default='mobile', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_sessions', 'client')
    # ### end Alembic commands ###
